version: '3'
services:

  pandoc:
    image: t3docs/wiki-migration
    build: ./pandoc

  composer-install:
    image: t3docs/wiki-migration
    user: "${UID}:${GID}"
    volumes:
      - .:/wiki-migration
    environment:
      - SCRIPT_VERBOSE=0
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        cd php && composer install;
      '

  composer-update:
    image: t3docs/wiki-migration
    user: "${UID}:${GID}"
    volumes:
      - .:/wiki-migration
    environment:
      - SCRIPT_VERBOSE=0
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        cd php && composer update;
      '

  convert:
    image: t3docs/wiki-migration
    user: "${UID}:${GID}"
    volumes:
      - .:/wiki-migration
    environment:
      - SCRIPT_VERBOSE=0
      - SCOPE
      - XDEBUG_CONFIG
      - PHP_IDE_CONFIG
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        if [ -n "$${XDEBUG_CONFIG}" ] && [ -n "$${PHP_IDE_CONFIG}" ]; then
          echo "Debugging enabled."
          php -c /etc/php/7.4/cli/php-debug.ini ./php/vendor/bin/wiki $${SCOPE};
        else
          echo "No debugging."
          ./php/vendor/bin/wiki $${SCOPE};
        fi
      '
