version: '3'
services:

  composer-install:
    image: t3docs/exception-pages-php
    user: "${UID}:${GID}"
    volumes:
      - ./app:/var/www/app
    environment:
      - SCRIPT_VERBOSE=0
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        cd app && composer install;
      '

  composer-update:
    image: t3docs/exception-pages-php
    user: "${UID}:${GID}"
    volumes:
      - ./app:/var/www/app
    environment:
      - SCRIPT_VERBOSE=0
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        cd app && composer update;
      '
