version: '3'
services:

  composer-install:
    image: t3docs/exception-pages-php
    user: "${UID}:${GID}"
    volumes:
      - ./app:/var/www/app
    environment:
      - SCRIPT_VERBOSE=0
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        cd app && composer install;
      '

  composer-update:
    image: t3docs/exception-pages-php
    user: "${UID}:${GID}"
    volumes:
      - ./app:/var/www/app
    environment:
      - SCRIPT_VERBOSE=0
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        cd app && composer update;
      '

  fetch-exception-code-files:
    image: t3docs/exception-pages-php
    user: "${UID}:${GID}"
    volumes:
      - ./app:/var/www/app
    environment:
      - SCRIPT_VERBOSE=0
      - TYPO3_RELEASE_PATTERN
      - FORCE
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        cd app && ./vendor/bin/fetch-exception-code-files "$${TYPO3_RELEASE_PATTERN}" "$${FORCE}";
      '

  merge-exception-code-files:
    image: t3docs/exception-pages-php
    user: "${UID}:${GID}"
    volumes:
      - ./app:/var/www/app
    environment:
      - SCRIPT_VERBOSE=0
      - TYPO3_RELEASE_PATTERN
      - FILE_NAME
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        cd app && ./vendor/bin/merge-exception-code-files "$${TYPO3_RELEASE_PATTERN}" "$${FILE_NAME}";
      '

  update-exception-code-files:
    image: t3docs/exception-pages-php
    user: "${UID}:${GID}"
    volumes:
      - ./app:/var/www/app
    environment:
      - SCRIPT_VERBOSE=0
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        cd app;
        ./vendor/bin/fetch-exception-code-files;
        ./vendor/bin/merge-exception-code-files;
      '
