version: '3'
services:

  php:
    image: t3docs/exception-pages-php
    build: ./php
    user: "${UID}:${GID}"
    volumes:
      - ./app:/var/www/app
      - ./html:/var/www/html

  nginx:
    image: t3docs/exception-pages-nginx
    build: ./nginx
    ports:
    - "8080:80"
    volumes:
      - ./nginx/files/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/app
      - ./html:/var/www/html
