name: Install

on:
  push:
    branches: [ susitest ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: cd create/app/ && composer install --prefer-dist --no-progress --no-suggest --no-dev

      - name: Find and Replace User Name - Using Build Variable
        run: |
          find create/app/config.inc.php -type f -exec sed -i ''s/#{USERNAME}#/${{ secrets.EXCEPTIONS_USER }}/g'' {} \;
          find create/app/config.inc.php -type f -exec sed -i ''s/#{TOKEN}#/${{ secrets.EXCEPTIONS_TOKEN }}/g'' {} \;
          cp create/app/config.inc.php create/app/config.php

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_DOCS_HOST }}
          username: ${{ secrets.DEPLOY_DOCS_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "create/app/*"
          target: "/srv/vhosts/prod.docs.typo3.com/deployment/github/"

